### PR TITLE
change: make compatible with PicoCMS v1.0

### PR DESCRIPTION
**Pull request by khartahk**
- changed default dir to cache/ to make the content folder cleaner
- changed preg_replace to rename filenames to urlencode because this
  function is arround 40% faster (could probably be improved)
- fixed config structure and added details to README.md
- changed $cacheDo variable to enabled so that it's using the one from
  the config
- renamed the file to the new specifications http://picocms.org/development/#plugins

### CODE REVIEW

**Comment by glumb** [comment]
Thanks for your PR. The plugin was renamed to `Pico_Xcache` to ensure it is loaded at the end. Is there a (better) way in Pico 1.0 to change the plugin loading order? Other plugins altering the content are not working when the cache caches the contents current state.

**Comment by primozcankar** [comment]
I've renamed the plugin back to Pico_Xcache. I don't know how to change the load order otherwise but we could ask the PicoCMS maintainer. I didn't mention it but I've added a url path that clears the cache if you use it: http://domain.tld/Clear_XcacheTrue.

**Comment by vollstock** [comment]
Apparently load order is supposed to be decided by renaming the plugin files:
http://picocms.org/phpDoc/master/classes/Pico.html#method_loadPlugins

why not ;-)

**Comment by vollstock** [comment]
My suggestion for a name would be “PageCache”.
I am writing a plugin that will create a responsive image cache and then there's the twig cache.

In my case now all now works in harmony:

Plugin folder:
```
plugins/
    […]
    80-ResponsiveImageCache.php
    81-PageCache.php
```

Cache folder:
```
cache/
    images/
    pages/  <- your plugin
    templates/ <-twig
```

**Pull request closed without merging**
